version: "3.7"
services:
  front:
    image: nginx
    volumes:
      - ./nginx_server.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/frontend:/var/www/front
    ports:
      - "80:80"
    environment:
#      - NGINX_HOST=foobar.com
      - NGINX_PORT=80