version: "3.9"
services:
  front:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
#      - NGINX_HOST=foobar.com
      - NGINX_PORT=80